### ISSUE TITLE
Missing package: Agda

### ISSUE THREAD

**Issue by asr** [nh2/hackage-download#2]
Using the current master (6ec9749146b234367d2ad6f98a186973d3d304d2) and

```bash
$ cabal --version
cabal-install version 2.4.1.0
compiled using version 2.4.1.0 of the Cabal library
```

The [Agda](https://hackage.haskell.org/package/Agda) package is not downloaded:

```
$ ./hackage-download.py --latest
$ ls -d Agda*
Agda-executable-2.3.0.1
```

**Comment by RyanGlScott** [comment]
Hm, I was unable to reproduce this when I tried a moment ago:

```
$ cabal --version
cabal-install version 3.0.1.0
compiled using version 3.0.1.0 of the Cabal library
$ ./hackage-download.py --latest
$ ls -d Agda*
Agda-2.6.0.1  Agda-executable-2.3.0.1
```

**Comment by asr** [comment]
I just tried again and I couldn't find `Agda-2.6.0.1` using

```
$ cabal --version
$ cabal-install version 3.0.0.0
compiled using version 3.0.0.0 of the Cabal library
```

Do you get `Agda-2.6.0.1` using this version of  `cabal-install`?

**Comment by RyanGlScott** [comment]
> Do you get Agda-2.6.0.1 using this version of `cabal-install`?

It's hard to say, since I'm not sure where you obtained your version of `cabal-install`. (I obtained mine from https://launchpad.net/~hvr/+archive/ubuntu/ghc, FWIW.)

**Comment by asr** [comment]
I got my version of `cabal-install` from [Hackage](https://hackage.haskell.org/package/cabal-install-3.0.0.0). What else could it be from? :-)

**Comment by RyanGlScott** [comment]
Good to know, I just wanted to verify since the difference between `3.0.0.0` and `3.0.1.0` is apparently significant enough to matter in this context. I'll report back when I successfully build `cabal-install` from source.

**Comment by RyanGlScott** [comment]
I'm afraid that I _still_ can't reproduce the behavior you're seeing with that version of `cabal-install`:

```
$ cabal --version
cabal-install version 3.0.0.0                                                                      
compiled using version 3.0.0.0 of the Cabal library
$ ./hackage-download.py --latest
$ ls -d Agda*
Agda-2.6.0.1  Agda-executable-2.3.0.1
```

**Comment by asr** [comment]
My problem is the same using `cabal-install 3.0.1.0` from [here](https://github.com/haskell/cabal/releases/tag/cabal-install-v3.0.1.0-rc4) and `Cabal-3.0.1.0` from [here](https://github.com/haskell/cabal/releases/tag/Cabal-v3.0.1.0-rc2):

```
$ cabal --version
cabal-install version 3.0.1.0
compiled using version 3.0.1.0 of the Cabal library
$ ./hackage-download.py --latest
$ ls -d Agda*
Agda-executable-2.3.0.1
```

**Comment by RyanGlScott** [comment]
I'm not sure what the issue could be then, since I can't reproduce those results on either version of `cabal-install`. Are you sure it's not an issue on your side? Does `wget --quiet http://hackage.haskell.org/package/Agda-2.6.0.1/Agda-2.6.0.1.tar.gz` work, for instance?

**Comment by asr** [comment]
> Are you sure it's not an issue on your side?

I don't know. I have the same problem in two different machines and from two different places (home and office).

> Does `wget --quiet http://hackage.haskell.org/package/Agda-2.6.0.1/Agda-2.6.0.1.tar.gz work`, for instance?

It works.

**Comment by RyanGlScott** [comment]
OK. Another shot in the dark: does `cabal list --simple | grep Agda` actually return any hits for `Agda-x.y.z`?

**Comment by asr** [comment]
> does `cabal list --simple | grep Agda` actually return any hits for `Agda-x.y.z`?

Yes.

```bash
$ cabal list --simple | grep '^Agda'
Agda 2.2.0
Agda 2.2.2
Agda 2.2.4
Agda 2.2.6
Agda 2.2.8
Agda 2.2.10
Agda 2.3.0
Agda 2.3.0.1
Agda 2.3.2
Agda 2.3.2.1
Agda 2.3.2.2
Agda 2.4.0
Agda 2.4.0.1
Agda 2.4.0.2
Agda 2.4.2
Agda 2.4.2.1
Agda 2.4.2.2
Agda 2.4.2.3
Agda 2.4.2.4
Agda 2.4.2.5
Agda 2.5.1
Agda 2.5.1.1
Agda 2.5.1.2
Agda 2.5.2
Agda 2.5.3
Agda 2.5.4
Agda 2.5.4.1
Agda 2.5.4.2
Agda 2.6.0
Agda 2.6.0.1
Agda-executable 2.2.0
Agda-executable 2.2.2
Agda-executable 2.2.4
Agda-executable 2.2.6
Agda-executable 2.2.8
Agda-executable 2.2.10
Agda-executable 2.3.0
Agda-executable 2.3.0.1

**Comment by asr** [comment]
Which version of Python are you using?

**Comment by RyanGlScott** [comment]
I'm using:

```
$ python3 --version
Python 3.6.9
```

Note that I'm displaying the results of `python3` since `hackage-download.py` specifies `#!/usr/bin/env python3` at the top.

**Comment by asr** [comment]
I can use different versions of Python via the [pyenv](https://realpython.com/intro-to-pyenv) tool. After installing Python 3.6.9, which solved my problem, I cannot reproduce my problem with other versions of Python. Thanks!
